# Generated by Django 5.0.14 on 2026-05-05 20:43

import datetime
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxBracketSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'ZIMRA 2026 — USD'", max_length=120)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZWG', 'Zimbabwe Gold'), ('ZWL', 'Zimbabwe Dollar (legacy)'), ('ZAR', 'South African Rand')], default='USD', max_length=8)),
                ('effective_from', models.DateField(default=datetime.date.today)),
                ('effective_to', models.DateField(blank=True, help_text="Leave blank to mean 'still active'", null=True)),
                ('aids_levy_rate', models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='AIDS Levy applied on top of PAYE. ZIMRA: 3.0% historically.', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-deactivate. Set false instead of deleting so historical payslip snapshots remain resolvable.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_brackets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-effective_from', 'currency'),
            },
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('lower', models.DecimalField(decimal_places=2, max_digits=14)),
                ('upper', models.DecimalField(blank=True, decimal_places=2, help_text='Inclusive upper bound; leave blank for ∞ (top bracket).', max_digits=14, null=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Marginal tax rate as a percentage. e.g. 25.00', max_digits=5)),
                ('fixed_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="ZIMRA-style 'subtract from rate × income' constant.", max_digits=14)),
                ('bracket_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='compliance.taxbracketset')),
            ],
            options={
                'ordering': ('bracket_set', 'sort_order', 'lower'),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('approve', 'Approved'), ('void', 'Voided')], max_length=16)),
                ('model_label', models.CharField(help_text='<app_label>.<ModelName>', max_length=120)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=240)),
                ('actor_username', models.CharField(blank=True, help_text="Captured at write time so user-rename doesn't lose attribution", max_length=150)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, help_text='Optional short reason / context', max_length=240)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['model_label', 'object_id'], name='compliance__model_l_ba7b16_idx'), models.Index(fields=['actor'], name='compliance__actor_i_81f1de_idx'), models.Index(fields=['action'], name='compliance__action_732645_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(choices=[('USD', 'US Dollar'), ('ZWG', 'Zimbabwe Gold'), ('ZWL', 'Zimbabwe Dollar (legacy)'), ('ZAR', 'South African Rand')], default='USD', max_length=8)),
                ('quote', models.CharField(choices=[('USD', 'US Dollar'), ('ZWG', 'Zimbabwe Gold'), ('ZWL', 'Zimbabwe Dollar (legacy)'), ('ZAR', 'South African Rand')], default='ZWG', max_length=8)),
                ('rate', models.DecimalField(decimal_places=6, help_text='1 base = N quote', max_digits=14)),
                ('as_of', models.DateField(default=datetime.date.today, help_text='Date this rate applies from')),
                ('notes', models.CharField(blank=True, help_text="e.g. 'RBZ interbank average'", max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_rates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-as_of', 'base', 'quote'),
                'indexes': [models.Index(fields=['base', 'quote', 'as_of'], name='compliance__base_a50a83_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatutoryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('nssa_employee_pct', 'NSSA Employee Contribution %'), ('nssa_employer_pct', 'NSSA Employer Contribution %'), ('nssa_ceiling', 'NSSA Insurable Earnings Ceiling'), ('aids_levy_pct', 'AIDS Levy %'), ('standard_ot_rate', 'Standard Overtime Multiplier (weekday)'), ('weekend_ot_rate', 'Overtime Multiplier (weekend / holiday)')], max_length=64)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('ZWG', 'Zimbabwe Gold'), ('ZWL', 'Zimbabwe Dollar (legacy)'), ('ZAR', 'South African Rand')], help_text='Currency-specific (e.g. NSSA ceiling); leave blank if rate-only (percent).', max_length=8)),
                ('effective_from', models.DateField(default=datetime.date.today)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statutory_rates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-effective_from', 'code', 'currency'),
                'indexes': [models.Index(fields=['code', 'currency', 'effective_from'], name='compliance__code_3755c2_idx'), models.Index(fields=['is_active'], name='compliance__is_acti_4e1cd8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='taxbracketset',
            index=models.Index(fields=['currency', 'effective_from'], name='compliance__currenc_d8a90c_idx'),
        ),
        migrations.AddIndex(
            model_name='taxbracketset',
            index=models.Index(fields=['is_active'], name='compliance__is_acti_fefca7_idx'),
        ),
        migrations.AddIndex(
            model_name='taxbracket',
            index=models.Index(fields=['bracket_set', 'lower'], name='compliance__bracket_055057_idx'),
        ),
    ]
