# Generated by Django 5.0.14 on 2026-05-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='module_access',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
