# Generated by Django 5.0.14 on 2026-09-23 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(db_index=True, max_length=64)),
                ('section', models.CharField(default='general', max_length=64)),
                ('key', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('text', 'Short text'), ('richtext', 'Paragraph'), ('image', 'Image'), ('url', 'Link / URL'), ('number', 'Number'), ('bool', 'Toggle')], default='text', max_length=16)),
                ('label', models.CharField(blank=True, help_text='Human name shown in the admin.', max_length=160)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('value', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('page', 'section', 'order', 'key'),
                'indexes': [models.Index(fields=['page', 'section'], name='website_con_page_2e1283_idx')],
                'unique_together': {('page', 'section', 'key')},
            },
        ),
    ]
