# Generated by Django 5.0.14 on 2026-09-23 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_seed_starter_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('alt', models.CharField(blank=True, help_text='Describe the image for accessibility & SEO.', max_length=300)),
                ('file', models.ImageField(blank=True, null=True, upload_to='website/media/')),
                ('external_url', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(choices=[('upload', 'Uploaded'), ('brand', 'Brand library')], default='upload', max_length=16)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('folder', models.CharField(blank=True, help_text='Optional grouping, e.g. a page name.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'title'),
                'indexes': [models.Index(fields=['source', 'folder'], name='website_med_source_cd2fb6_idx')],
            },
        ),
    ]
