# Generated by Django 5.0.14 on 2026-05-11 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_issue_date_alter_quotation_issue_date_and_more'),
        ('crm', '0003_projectcost_is_billable_projectcost_paid_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer the quotation is for, when no project has been opened yet.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='recipient_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='recipient_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='quotation',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Free-form recipient when neither project nor customer is set.', max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='crm.project'),
        ),
    ]
