# Generated by Django 5.0.14 on 2026-05-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_customer_invoice_recipient_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='section',
            field=models.CharField(blank=True, help_text='Optional grouping label (Bathroom, Lounge, …). Items in the same section render under one subheader on the PDF.', max_length=80),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='section',
            field=models.CharField(blank=True, help_text="Optional grouping label, e.g. 'Bathroom', 'Lounge', 'Master Suite'. Items sharing a section render under one subheader on the PDF.", max_length=80),
        ),
    ]
