# Generated by Django 5.0.14 on 2026-05-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoiceitem_section_quotationitem_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='recipient_tin',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recipient_vat',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='quotation',
            name='recipient_tin',
            field=models.CharField(blank=True, help_text='Free-form recipient TIN / BP number.', max_length=40),
        ),
        migrations.AddField(
            model_name='quotation',
            name='recipient_vat',
            field=models.CharField(blank=True, help_text='Free-form recipient VAT number.', max_length=40),
        ),
    ]
