# Generated by Django 5.0.14 on 2026-07-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoice_recipient_tin_invoice_recipient_vat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='kind',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('proforma', 'Proforma Invoice')], default='invoice', help_text="'proforma' for a preliminary bill (PI- series); 'invoice' for a real invoice (INV- series).", max_length=12),
        ),
    ]
