# Generated by Django 5.0.14 on 2026-05-06 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ProjectCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=240)),
                ('category', models.CharField(choices=[('materials', 'Materials'), ('labour', 'Labour'), ('transport', 'Transport'), ('permits', 'Permits & fees'), ('equipment', 'Equipment hire'), ('subcontract', 'Subcontract'), ('overhead', 'Overhead'), ('other', 'Other')], default='other', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('incurred_on', models.DateField()),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('receipt_reference', models.CharField(blank=True, help_text='External receipt / invoice number, if any.', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_costs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='crm.project')),
            ],
            options={
                'ordering': ('-incurred_on', '-created_at'),
                'indexes': [models.Index(fields=['project', 'incurred_on'], name='crm_project_project_1390f4_idx'), models.Index(fields=['category'], name='crm_project_categor_8fcb2e_idx')],
            },
        ),
    ]
