# Generated by Django 5.0.14 on 2026-05-11 12:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_project_latitude_project_longitude_projectcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcost',
            name='is_billable',
            field=models.BooleanField(default=False, help_text='Marks the expense as on-bill to a client (typically only when a project is attached).'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='paid_on',
            field=models.DateField(blank=True, help_text='When the expense was paid. Leave blank for unpaid / pending.', null=True),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('mobile_money', 'Mobile money'), ('card', 'Card'), ('cheque', 'Cheque'), ('other', 'Other')], default='bank_transfer', max_length=16),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='receipt_url',
            field=models.URLField(blank=True, help_text='Link to the scanned receipt or invoice (e.g. DO Spaces upload).'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='VAT or other tax portion of the amount, if recorded separately.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='projectcost',
            name='category',
            field=models.CharField(choices=[('materials', 'Materials'), ('labour', 'Labour'), ('transport', 'Transport'), ('permits', 'Permits & fees'), ('equipment', 'Equipment hire'), ('subcontract', 'Subcontract'), ('overhead', 'Overhead'), ('office', 'Office'), ('marketing', 'Marketing'), ('fuel', 'Fuel & vehicle'), ('utilities', 'Utilities'), ('software', 'Software & subscriptions'), ('entertainment', 'Client entertainment'), ('other', 'Other')], default='other', max_length=24),
        ),
        migrations.AlterField(
            model_name='projectcost',
            name='incurred_on',
            field=models.DateField(help_text='Date the expense was actually incurred.'),
        ),
        migrations.AlterField(
            model_name='projectcost',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Optional. Leave blank for global / overhead expenses.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='crm.project'),
        ),
        migrations.AlterField(
            model_name='projectcost',
            name='supplier',
            field=models.CharField(blank=True, help_text='Vendor or supplier name.', max_length=200),
        ),
    ]
