# Generated by Django 5.0.14 on 2026-05-13 11:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoiceitem_section_quotationitem_section'),
        ('crm', '0003_projectcost_is_billable_projectcost_paid_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='service', max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('short_code', models.CharField(blank=True, db_index=True, help_text='Internal SKU / shorthand to recognise the item quickly.', max_length=40)),
                ('description', models.TextField(blank=True, help_text='Long-form description; surfaces verbatim on the quote/invoice line.')),
                ('default_unit', models.CharField(default='m²', max_length=16)),
                ('default_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('times_used', models.IntegerField(default=0, help_text='Bumped each time the item is invoked in a quotation/invoice line.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
                'indexes': [models.Index(fields=['kind'], name='crm_catalog_kind_05d492_idx'), models.Index(fields=['is_active'], name='crm_catalog_is_acti_7c2295_idx')],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('invoice_receipt', 'Invoice receipt'), ('cash_sale', 'Cash sale'), ('loan_received', 'Loan received'), ('owner_capital', 'Owner capital injection'), ('refund', 'Refund / rebate'), ('interest', 'Interest earned'), ('rental', 'Rental / sublease'), ('other', 'Other')], default='cash_sale', help_text='What channel this money came through.', max_length=24)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('received_on', models.DateField(help_text='Date the money was received.')),
                ('method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('mobile_money', 'Mobile money'), ('cheque', 'Cheque'), ('card', 'Card'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('payer', models.CharField(blank=True, help_text="Who paid. 'Walk-in client', 'CBZ Bank', a customer name, etc.", max_length=200)),
                ('reference', models.CharField(blank=True, help_text='Bank reference, deposit slip number, EcoCash txn id…', max_length=120)),
                ('receipt_url', models.URLField(blank=True, help_text='Link to a scanned bank slip / deposit (DO Spaces).')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes_recorded', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Optional. Attribute to a project when relevant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='crm.project')),
                ('receipt', models.OneToOneField(blank=True, help_text='Set automatically when this Income mirrors an invoice receipt.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income', to='billing.receipt')),
            ],
            options={
                'ordering': ('-received_on', '-created_at'),
                'indexes': [models.Index(fields=['received_on'], name='crm_income_receive_768521_idx'), models.Index(fields=['source'], name='crm_income_source_5d0601_idx'), models.Index(fields=['currency'], name='crm_income_currenc_43e06d_idx')],
            },
        ),
    ]
