# Generated by Django 5.0.14 on 2026-05-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_catalogitem_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tin_number',
            field=models.CharField(blank=True, help_text='Taxpayer Identification Number (ZIMRA TIN / BP number).', max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, help_text='VAT registration number, if the client is VAT-registered.', max_length=40),
        ),
    ]
