# Generated by Django 5.0.14 on 2026-05-22 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customer_tin_number_customer_vat_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='site_visit_date',
            field=models.DateField(blank=True, help_text='When the visit is scheduled for, or the date it was done.', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='site_visit_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='site_visit_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('required', 'To be done'), ('done', 'Done')], default='not_required', max_length=16),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['site_visit_status'], name='crm_custome_site_vi_27503f_idx'),
        ),
    ]
