# Generated by Django 5.0.14 on 2026-06-11 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_customer_site_visit_date_customer_site_visit_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('drawing', 'Drawing / Plan'), ('photo', 'Photo'), ('document', 'Document'), ('other', 'Other')], default='drawing', max_length=16)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='customer_files/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crm.customer')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_on', models.DateField(help_text='Date this part-payment was made.')),
                ('method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('mobile_money', 'Mobile money'), ('card', 'Card'), ('cheque', 'Cheque'), ('other', 'Other')], default='bank_transfer', max_length=16)),
                ('reference', models.CharField(blank=True, help_text='Bank ref, txn id, cheque #…', max_length=120)),
                ('note', models.CharField(blank=True, help_text="e.g. 'Deposit', 'Final on completion'.", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_payments', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.projectcost')),
            ],
            options={
                'ordering': ('paid_on', 'created_at'),
                'indexes': [models.Index(fields=['expense', 'paid_on'], name='crm_expense_expense_a0dd66_idx')],
            },
        ),
    ]
