# Generated by Django 5.0.14 on 2026-09-07 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_backfill_expense_payments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('title', models.CharField(blank=True, help_text="What the client sees, e.g. 'Lounge — stretch ceiling concept'.", max_length=200)),
                ('client_name', models.CharField(blank=True, help_text="Burned into the watermark — defaults to the customer's name.", max_length=200)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('require_passcode', models.BooleanField(default=False)),
                ('passcode_hash', models.CharField(blank=True, max_length=256)),
                ('allow_download', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_shares_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_shares', to='crm.customer')),
                ('files', models.ManyToManyField(blank=True, related_name='design_shares', to='crm.projectfile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_shares', to='crm.project')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DesignShareView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.projectfile')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='crm.designshare')),
            ],
            options={
                'ordering': ('-viewed_at',),
            },
        ),
        migrations.AddIndex(
            model_name='designshare',
            index=models.Index(fields=['token'], name='crm_designs_token_001297_idx'),
        ),
    ]
