# Generated by Django 5.0.14 on 2026-05-07 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('event', models.CharField(choices=[('low_stock', 'Low stock'), ('po_received', 'PO received'), ('po_overdue', 'PO overdue')], max_length=24)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('inapp', 'In-app')], max_length=12)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, help_text='E.164 format: +263…', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('event', 'channel', 'name'),
            },
        ),
        migrations.AddField(
            model_name='item',
            name='last_low_stock_alert_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last low-stock alert sent for this item — used to suppress repeats.', null=True),
        ),
        migrations.AddField(
            model_name='movement',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Public URL of the rendered PO PDF (DO Spaces in prod).', max_length=500),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=24)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('inapp', 'In-app')], max_length=12)),
                ('recipient', models.CharField(help_text='email or phone — denormalised so we can audit even after the rule is deleted.', max_length=240)),
                ('subject', models.CharField(blank=True, max_length=240)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=12)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='inventory.item')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='inventory.notificationrule')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['item', 'event', 'created_at'], name='inventory_n_item_id_f48cee_idx')],
            },
        ),
    ]
