# Generated by Django 5.0.14 on 2026-05-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_notificationrule_item_last_low_stock_alert_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size_spec',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
