# Generated by Django 5.0.14 on 2026-05-05 04:57

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, help_text='Auto: EMP-####', max_length=24, unique=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('national_id', models.CharField(blank=True, max_length=64)),
                ('tax_id', models.CharField(blank=True, help_text='Pay-As-You-Earn / tax number if applicable', max_length=64)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], default='active', max_length=16)),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('pay_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Biweekly'), ('weekly', 'Weekly')], default='monthly', max_length=16)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('default_allowances', models.JSONField(blank=True, default=list, help_text='[{name, amount}] applied per period by default')),
                ('default_deductions', models.JSONField(blank=True, default=list, help_text='[{name, amount}] applied per period by default')),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('bank_account', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
                'indexes': [models.Index(fields=['employee_code'], name='payroll_emp_employe_b2acf6_idx'), models.Index(fields=['status'], name='payroll_emp_status_98fdd7_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'May 2026' or 'Week 18 — 2026'", max_length=120)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_periods_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-period_end', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('allowances', models.JSONField(blank=True, default=list)),
                ('deductions', models.JSONField(blank=True, default=list)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('gross', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to='payroll.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ('employee__first_name', 'employee__last_name'),
                'indexes': [models.Index(fields=['period', 'employee'], name='payroll_pay_period__7c65fa_idx')],
                'unique_together': {('period', 'employee')},
            },
        ),
    ]
