# Generated by Django 5.0.14 on 2026-05-05 20:43

import compliance.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_employee_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='currency_split',
            field=models.JSONField(blank=True, default=list, help_text='[{"currency": "USD", "percent": 60}, {"currency": "ZWG", "percent": 40}]'),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='aids_levy',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='auto_compute_statutory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='currency_split',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='nssa_employee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='nssa_employer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='paye',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='statutory_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='tax_calc_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='exchange_rate_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='total_statutory',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account',
            field=compliance.fields.EncryptedTextField(blank=True),
        ),
    ]
