# Generated by Django 5.0.14 on 2026-05-05 22:12

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_employee_currency_split_payrollentry_aids_levy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('paid', models.BooleanField(default=True, help_text='Unpaid leave reduces gross during the period it falls in.')),
                ('accrual_per_month', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Days credited per month worked. 0 = lump-sum or no auto-accrual.', max_digits=6)),
                ('annual_cap', models.DecimalField(blank=True, decimal_places=2, help_text="Maximum balance days; balance won't accrue above this. Blank = uncapped.", max_digits=6, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField(unique=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='approval_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_periods_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_periods_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_periods_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='reopened_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of times this period has been reopened after CLOSED.'),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_periods_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('paid', 'Paid'), ('closed', 'Closed')], default='draft', max_length=16),
        ),
        migrations.CreateModel(
            name='EmployeeLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Auto: LN-####', max_length=24, unique=True)),
                ('kind', models.CharField(choices=[('loan', 'Loan'), ('advance', 'Salary Advance')], default='loan', max_length=16)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Annual interest rate %; 0 for interest-free.', max_digits=5)),
                ('instalment', models.DecimalField(decimal_places=2, help_text='Per-period deduction amount.', max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('issued_on', models.DateField(default=datetime.date.today)),
                ('first_repayment_period', models.DateField(blank=True, help_text='Earliest period_end the instalment applies to. Blank = next period.', null=True)),
                ('end_on', models.DateField(blank=True, help_text='Manual override; otherwise auto-calculated when settled.', null=True)),
                ('total_repaid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('settled', 'Settled'), ('written_off', 'Written off'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='payroll.employee')),
            ],
            options={
                'ordering': ('-issued_on', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=2, help_text='Working days; supports half-days as 0.5.', max_digits=6)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('consumed', 'Consumed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_created', to=settings.AUTH_USER_MODEL)),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_decisions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='payroll.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='payroll.leavetype')),
            ],
            options={
                'ordering': ('-start_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('last_accrued_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='payroll.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.leavetype')),
            ],
            options={
                'ordering': ('employee__first_name', 'leave_type__sort_order'),
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applied_on', models.DateField(default=datetime.date.today)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='payroll.employeeloan')),
                ('payroll_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayments', to='payroll.payrollentry')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayments', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ('-applied_on', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Leave blank for the current rate.', null=True)),
                ('reason', models.CharField(blank=True, help_text="e.g. 'Annual review 2026', 'Promotion to Senior Installer'", max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_history_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='payroll.employee')),
            ],
            options={
                'ordering': ('-effective_from', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='employeeloan',
            index=models.Index(fields=['employee', 'status'], name='payroll_emp_employe_8c4cf1_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'status'], name='payroll_lea_employe_797d55_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date'], name='payroll_lea_start_d_d175ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type')},
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['loan', 'period'], name='payroll_loa_loan_id_37d803_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryhistory',
            index=models.Index(fields=['employee', 'effective_from'], name='payroll_sal_employe_b9e860_idx'),
        ),
    ]
