# Generated by Django 5.0.14 on 2026-05-06 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_leavetype_publicholiday_payrollperiod_approval_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text='Free-text where the clock-in happened — site name, address.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_entries', to='payroll.employee')),
            ],
            options={
                'ordering': ['-clock_in'],
                'indexes': [models.Index(fields=['employee', 'clock_in'], name='payroll_clo_employe_e2a603_idx')],
            },
        ),
    ]
