# Generated by Django 5.0.14 on 2026-05-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_clockentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='home_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, help_text='e.g. Spouse, Mother, Brother, Friend.', max_length=60),
        ),
    ]
