# Generated by Django 5.0.14 on 2026-06-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_employee_total_remuneration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollentry',
            name='auto_compute_statutory',
            field=models.BooleanField(default=False),
        ),
    ]
