# Generated by Django 5.0.14 on 2026-08-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_alter_payrollentry_auto_compute_statutory'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollentry',
            name='salary_is_net',
            field=models.BooleanField(default=True),
        ),
    ]
