# Generated by Django 5.0.14 on 2026-09-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_payrollentry_salary_is_net'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('part_time', 'Part-time'), ('contract', 'Contract / Fixed-term'), ('service_provider', 'Service provider')], default='permanent', help_text='Permanent, part-time, contract or service provider — lets non-everyday staff be paid & reported separately.', max_length=20),
        ),
    ]
